#!/bin/bash
# wget -qO - http://gitea.casa.dylgran.com/yuniel/internet-etecsa-login/raw/branch/master/install | sudo bash

##  Bash settings
# abort on nonzero exitstatus
set -o errexit
# abort on unbound variable
set -o nounset
# don't hide errors within pipes
# set -o pipefail
# debug
# set -o xtrace
##

readonly UNAME=nauta # este usuario tiene que ser el mismo del .service
readonly INSTALL_DIR='/opt/internet-etecsa-login'

apt update -y
apt install -y git curl
# download
cd /opt/
git clone 'http://gitea.casa.dylgran.com/yuniel/internet-etecsa-login.git'
cd "$INSTALL_DIR"
chmod --verbose +x 'bin/internet-etecsa-login' uninstall update
# install dependencies
curl -sL 'https://deb.nodesource.com/setup_10.x' | sudo -E bash -
apt install -y nodejs build-essential jq
npm install npm@latest -g --unsafe-perm=true
npm install --production --unsafe-perm=true
# configure
ln --verbose -s "${INSTALL_DIR}/service/internet-etecsa-login.service" '/etc/systemd/system/internet-etecsa-login.service'
ln --verbose -s "${INSTALL_DIR}/desktop/internet-etecsa-login.desktop" '/usr/share/applications/internet-etecsa-login.desktop'
useradd --create-home --shell /bin/bash "$UNAME"
cp --verbose '.env-prod' '.env'
touch '/var/log/internet-etecsa-login.log'
chown "${UNAME}:${UNAME}" '/var/log/internet-etecsa-login.log'
# end
cat <<EOF

-------------------------------------------------------------------------------
>1: Edite al archivo .env y defina las credenciales de su cuenta nauta:
$ sudo nano ${INSTALL_DIR}/.env

>2: Proteja el archivo .env después de editarlo
$ sudo chown ${UNAME}:${UNAME} ${INSTALL_DIR}/.env
$ sudo chmod 400 ${INSTALL_DIR}/.env

>3: Después de haber completado los pasos 1 y 2 Instale el servicio
sudo systemctl enable internet-etecsa-login --now

>4: Ejecute la app 'Internet Login' para conectarse y desconectarse a internet,
>Asigne una tecla al comando 'gtk-launch internet-etecsa-login' para conectarse
>y desconectarse presionando una tecla, pruebe asignarle 'F9'.
-------------------------------------------------------------------------------
EOF


